plugins {
    id 'java'
    id 'groovy'
    id 'kotlin'
    id 'maven-publish'
}


dependencies {

    //gradle sdk
    implementation gradleApi()
    //groovy sdk
    implementation localGroovy()
    implementation 'com.android.tools.build:gradle:8.1.0'
    implementation 'com.android.tools.build:gradle-api:8.1.0'
    implementation 'org.ow2.asm:asm:9.1'
    implementation 'org.ow2.asm:asm-util:9.1'
    implementation 'org.ow2.asm:asm-commons:9.1'
}

version = "1.0.2"
group = "com.example.gradle_plugin"

publishing {
    repositories { RepositoryHandler handler ->
        handler.maven { MavenArtifactRepository mavenArtifactRepository -> //正式仓库
            url uri('../repos')
            allowInsecureProtocol = true
            if (url.toString().startsWith("http")) {
                credentials {
                    username = ''
                    password = ''
                }
            }
        }
    }

    publications { PublicationContainer publication ->
        maven(MavenPublication) {
            version version
            artifactId 'TracePlugin'
            groupId group
            from components.java
        }
    }
}
